name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm install; fi
          if [ -f src/package.json ]; then cd src && npm install && cd ..; fi
      - name: Run tests
        run: |
          if [ -f package.json ] && grep -q '"test"' package.json; then npm test; fi
          if [ -f src/package.json ] && grep -q '"test"' src/package.json; then cd src && npm test && cd ..; fi
