name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js latest
              uses: actions/setup-node@v4
              with:
                  node-version: 'latest'
            - name: Install dependencies
              run: |
                  if [ -f package.json ]; then npm ci; fi
                  if [ -f src/package.json ]; then cd src && npm ci && cd ..; fi
            - name: Run tests
              run: |
                  if [ -f package.json ] && grep -q '"test"' package.json; then npm test; fi
                  if [ -f src/package.json ] && grep -q '"test"' src/package.json; then cd src && npm test && cd ..; fi

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - uses: actions/checkout@v4
            - name: Deploy to Cloudflare Workers
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
