name: Generate Wrangler Types

on:
  schedule:
    - cron: "0 12 * * *" # every day at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  generate-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm ci

      - name: Generate Wrangler types
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler types

      - name: Get Wrangler version
        id: wrangler_version
        run: |
          npx wrangler --version > wrangler-version.txt
          echo "version=$(cat wrangler-version.txt)" >> $GITHUB_OUTPUT

      - name: Format generated types with Prettier
        run: npx prettier --write "*.d.ts"

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet HEAD -- "*.d.ts"; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore: regenerate Wrangler types with wrangler ${{ steps.wrangler_version.outputs.version }}

            This commit updates the Cloudflare Workers type definitions
            to ensure compatibility with the latest dependency versions.
            The types are automatically generated by 'wrangler types' (wrangler ${{ steps.wrangler_version.outputs.version }})
            to reflect any changes in the Cloudflare Workers runtime API.
          title: "chore: regenerate Wrangler types with wrangler ${{ steps.wrangler_version.outputs.version }}"
          body: |
            ## Automatic Wrangler Types Update

            This PR automatically regenerates the Cloudflare Workers type
            definitions for wrangler ${{ steps.wrangler_version.outputs.version }}.

            ### Changes
            - Updated `*.d.ts` files generated by `wrangler types`
            - Formatted with Prettier for consistency

            ### Why?
            When dependencies are updated, the Cloudflare Workers runtime API might change, requiring updated type definitions to ensure type safety and compatibility.

            ### Review
            Please review the generated type changes to ensure they're correct and don't break existing functionality.

            ---
            *This PR was automatically created by the Generate Wrangler Types workflow.*
          branch: update-wrangler-types-${{ github.run_number }}
          branch-suffix: timestamp
          delete-branch: true
          sign-commits: true
          signoff: true
          labels: |
            javascript
